name: PyInstaller

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest"]

    env:
      MAIN_FILE: '"./cs2tracker/__main__.py"'
      NAME: '"cs2tracker"'
      ICON: '"./assets/icon.png"'
      ICON_INCLUDE: '"./assets/icon.png;./assets"'
      DATA_DIR_INCLUDE: '"./cs2tracker/data;./data"'
      NODE_MODULES_INCLUDE: '"./node_modules;./node_modules"'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: npm install steam-user globaloffensive axios @node-steam/vdf

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Locate eurofxref-hist.zip
        run: |
          if [[ "${{matrix.os}}" == "windows-latest" ]]; then
            $ZIP_PATH = python -c "import currency_converter, os; print(os.path.join(os.path.dirname(currency_converter.__file__), 'eurofxref-hist.zip'))"
            echo "CURRENCY_INCLUDE='$ZIP_PATH;./currency_converter'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          else
            ZIP_PATH=$(python -c "import currency_converter, os; print(os.path.join(os.path.dirname(currency_converter.__file__), 'eurofxref-hist.zip'))")
            echo "CURRENCY_INCLUDE=$ZIP_PATH:./currency_converter" >> $GITHUB_ENV
          fi

      - name: Locate nodejs-bin files
        run: |
          if [[ "${{matrix.os}}" == "windows-latest" ]]; then
            $NODE_BIN_PATH = python -c "import nodejs, os; print(os.path.dirname(nodejs.__file__))"
            echo "NODE_BIN_INCLUDE='$NODE_BIN_PATH;./nodejs'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          else
            NODE_BIN_PATH=$(python -c "import nodejs, os; print(os.path.dirname(nodejs.__file__))")
            echo "NODE_BIN_INCLUDE=$NODE_BIN_PATH:./nodejs" >> $GITHUB_ENV
          fi

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed --name ${{ env.NAME }} --icon ${{ env.ICON }} `
            --add-data ${{ env.ICON_INCLUDE }} `
            --add-data ${{ env.DATA_DIR_INCLUDE }} `
            --add-data ${{ env.NODE_MODULES_INCLUDE }} `
            --add-data ${{ env.CURRENCY_INCLUDE }} `
            --add-data ${{ env.NODE_BIN_INCLUDE }} `
            ${{ env.MAIN_FILE }}

      - name: List files in dist folder
        run: ls -R dist/

      - name: Zip windows executable
        run: |
          if [[ "${{matrix.os}}" == "windows-latest" ]]; then
            Compress-Archive -Path "dist/cs2tracker.exe" -DestinationPath "cs2tracker-windows.zip"
          else
            zip cs2tracker-linux.zip dist/cs2tracker

      - name: Generate SHA256 checksum
        run: |
          if [[ "${{matrix.os}}" == "windows-latest" ]]; then
            shasum -a 256 cs2tracker-windows.zip > cs2tracker-windows.zip.sha256
          else
            shasum -a 256 cs2tracker-linux.zip > cs2tracker-linux.zip.sha256

      - name: Upload windows executable
        if: matrix.os == 'windows-latest'
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["cs2tracker-windows.zip", "cs2tracker-windows.zip.sha256"]'

      - name: Upload linux executable
        if: matrix.os == 'ubuntu-latest'
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["cs2tracker-linux.zip", "cs2tracker-linux.zip.sha256"]'
