name: PyInstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"] # Currently, other OS's are not supported

    env:
      MAIN_FILE: "./cs2tracker/__main__.py"
      ICON: "./assets/icons8-counter-strike-bubbles-96.png"
      CONFIG: "./cs2tracker/data/config.ini;./data"
      OUTPUT: "./cs2tracker/data/output.csv;./data"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Locate eurofxref-hist.zip
        run: |
          $ZIP_PATH = python -c "import currency_converter, os; print(os.path.join(os.path.dirname(currency_converter.__file__), 'eurofxref-hist.zip'))"
          echo "CURRENCY=$ZIP_PATH;./currency_converter" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build executable
        run: pyinstaller --noconfirm --onefile --windowed --icon ${{ env.ICON }} --add-data ${{ env.CONFIG }} --add-data ${{ env.OUTPUT }} --add-data ${{ env.CURRENCY }} ${{ env.MAIN_FILE }}

      - name: Create Artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/
