name: PyInstaller

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"] # Currently, other OS's are not supported

    env:
      MAIN_FILE: '"./cs2tracker/__main__.py"'
      ICON: '"./assets/icon.png"'
      CONFIG_DATA: '"./cs2tracker/data/config.ini;./data"'
      OUTPUT_DATA: '"./cs2tracker/data/output.csv;./data"'
      ICON_DATA: '"./assets/icon.png;./assets"'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Locate eurofxref-hist.zip
        run: |
          $ZIP_PATH = python -c "import currency_converter, os; print(os.path.join(os.path.dirname(currency_converter.__file__), 'eurofxref-hist.zip'))"
          echo "CURRENCY_DATA='$ZIP_PATH;./currency_converter'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build executable
        run: pyinstaller --noconfirm --onefile --windowed --name "cs2tracker" --icon ${{ env.ICON }} --add-data ${{ env.ICON_DATA }} --add-data ${{ env.CONFIG_DATA }} --add-data ${{ env.OUTPUT_DATA }} --add-data ${{ env.CURRENCY_DATA }} ${{ env.MAIN_FILE }}

      - name: List files in dist folder
        run: ls -R dist/

      - name: Zip windows executable
        run: Compress-Archive -Path "dist/cs2tracker.exe" -DestinationPath "cs2tracker-windows.zip"

      - name: Generate SHA256 checksum
        run: shasum -a 256 cs2tracker-windows.zip > cs2tracker-windows.zip.sha256

      - name: Upload windows executable
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["cs2tracker-windows.zip", "cs2tracker-windows.zip.sha256"]'
